version: '3.9'

services:
 mongodb:
  image: mongo
  ports:
   - "27017:27017"

 backend:
  build: ./API-mensagens
  ports:
   - "8000:8000"
  depends_on:
   - mongodb

 frontend:
  build: ./my-react-app
  ports:
   - "3000:3000"