version: '3.9'

services:
 mongodb:
  image: mongo
  ports:
   - "27017:27017"
  

 backend:
  build: ./API-mensagens
  ports:
   - "5000:5000"
  env_file:
   - ./API-mensagens/.env 
  
  depends_on:
   - mongodb

 frontend:
  build: ./my-react-app
  ports:
   - "5173:5173"
  
  depends_on:
   - backend 

